from __future__ import annotations

import json
import logging
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from threading import RLock
from typing import Any, Dict, List

from agno.filters import EQ, OR
from agno.models.message import Message

import uvicorn
from fastapi import FastAPI, Request
from starlette.responses import Response

from logistics_agent import MCP_SERVER_URL, centrala_mcp_server, agno_assist, OperatorRequest, OperatorResponse, \
    messages_to_dict
from settings import logger
from stock_agent import agno_stock_assist, load_stock_knowledge, StockParams, StockApiResponse, stock_vector_db

# In-memory session store: sessionID -> messages (conversation history)
# Each message is a dict for flexibility.
_sessions: Dict[str, List[Dict[str, Any]]] = {}
_sessions_lock = RLock()


@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info(f"{MCP_SERVER_URL=}")
    try:
        logger.info("Centrala MCP: connect")
        await centrala_mcp_server.connect()

        logger.info("Centrala MCP: build tools")
        await centrala_mcp_server.build_tools()

        if centrala_mcp_server.tools:
            logger.info(
                f"MCP tools built: {len(centrala_mcp_server.tools)}; names={[getattr(t, 'name', str(t)) for t in centrala_mcp_server.tools]}")
        if centrala_mcp_server.functions:
            logger.info(f"MCP functions built: {len(centrala_mcp_server.functions)}; "
                        f"names={[getattr(t, 'name', str(t)) for t in centrala_mcp_server.functions]}")

        agno_assist.initialize_agent()
    except Exception:
        logger.exception("MCP init failed (connect/build_tools)")
        raise

    try:
        agno_stock_assist.initialize_agent()
        await load_stock_knowledge("./knowledge_resource")
        logger.info(f"{stock_vector_db.get_count()=}")

        from chromadb import PersistentClient
        chroma = PersistentClient("tmp/chromadb")
        collection = chroma.get_collection("stock_information")
        logger.info(f"{collection.count()=}")

    except Exception:
        logger.exception("Failed to initialize AGNO Stock Assistant")
        raise

    yield


# Disable autogenerated docs to keep the server effectively to a single endpoint.
app = FastAPI(docs_url=None, redoc_url=None, openapi_url=None, lifespan=lifespan)


@app.middleware("http")
async def log_request_response(request: Request, call_next):
    # request body
    req_body = await request.body()

    # call endpoint
    response = await call_next(request)

    # response body (consume iterator and rebuild response)
    resp_body = b""
    async for chunk in response.body_iterator:
        resp_body += chunk

    return Response(
        content=resp_body,
        status_code=response.status_code,
        headers=dict(response.headers),
        media_type=response.media_type,
        background=response.background,
    )


@app.post("/")
async def handle_message(payload: OperatorRequest) -> OperatorResponse:
    # Sprawdź czy toolsy się zainicjalizowały
    await centrala_mcp_server.connect()
    await centrala_mcp_server.build_tools()

    # print(f"MCP Tools initialized: {centrala_mcp_server.initialized}")
    # print(f"Available tools: {list(centrala_mcp_server.functions.keys())}")

    now = datetime.now(timezone.utc).isoformat()

    with _sessions_lock:
        history = _sessions.setdefault(payload.sessionID, [])
        history.append({"role": "operator", "msg": payload.msg, "ts": now})
        response = await agno_assist.arun(
            input=Message(
                role="user",
                content=payload.msg
            ),
            session_id=payload.sessionID,
        )

        messages = messages_to_dict(response.messages)
        logger.info(f"\nSESJA: {payload.sessionID}\n{json.dumps(messages, indent=4, ensure_ascii=False)}")
        history.append({"role": "server", "msg": response, "ts": now})

    return OperatorResponse(msg=response.messages[-1].content)


@app.post("/api/stock_index")
async def stock_index_api(params: StockParams) -> StockApiResponse:
    """ Api to check magazines in mutliple cities
    :param params: Ask question about stock of items in mutliple cities. Either does given list of items is in city X, or in what cities given item is stored. As item you can provide either name or item code.
    :return:
    """

    def extract_simple_response(messages) -> str:
        content = messages[-1].content
        logger.info(f"{content=}")
        if isinstance(content, list):
            output = "\n".join(content)
        else:
            output = str(content)
        return output

    logger.info(f"{params=}")

    response = await agno_stock_assist.arun(params)
    output = extract_simple_response(response.messages)

    response_fix = await agno_stock_assist.arun(f"Jeżeli treść zawiera kody miast, odkoduj je. "
                                                f"Po za tym zwróć wiadomość NIEZMIENIONĄ: '{output}'",
                                                knowledge_filters={"name": "cities.csv"})
    output_final = extract_simple_response(response_fix.messages)

    return StockApiResponse(output=output_final)


if __name__ == "__main__":
    centrala_mcp_server.connect()
    centrala_mcp_server.build_tools()
    uvicorn.run("main:app", host="0.0.0.0", port=3000, reload=False)
