from __future__ import annotations

import logging
import sys
from datetime import datetime, timezone
from threading import RLock
from typing import Any, Dict, List

import uvicorn
from fastapi import FastAPI, Request
from pydantic import BaseModel, Field
from starlette.responses import Response

# --- logging to stdout ---
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s - %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger("app")

# In-memory session store: sessionID -> messages (conversation history)
# Each message is a dict for flexibility.
_sessions: Dict[str, List[Dict[str, Any]]] = {}
_sessions_lock = RLock()

# Disable autogenerated docs to keep the server effectively to a single endpoint.
app = FastAPI(docs_url=None, redoc_url=None, openapi_url=None)


@app.middleware("http")
async def log_request_response(request: Request, call_next):
    # request body
    req_body = await request.body()
    req_body_text = req_body.decode("utf-8", errors="replace")

    # call endpoint
    response = await call_next(request)

    # response body (consume iterator and rebuild response)
    resp_body = b""
    async for chunk in response.body_iterator:
        resp_body += chunk
    resp_body_text = resp_body.decode("utf-8", errors="replace")

    logger.info(
        "REQ %s %s body=%s",
        request.method,
        str(request.url),
        req_body_text,
    )
    logger.info(
        "RESP %s %s status=%s body=%s",
        request.method,
        str(request.url),
        response.status_code,
        resp_body_text,
    )

    return Response(
        content=resp_body,
        status_code=response.status_code,
        headers=dict(response.headers),
        media_type=response.media_type,
        background=response.background,
    )


class OperatorRequest(BaseModel):
    sessionID: str = Field(..., min_length=1)
    msg: str = Field(..., min_length=1)


class OperatorResponse(BaseModel):
    msg: str


@app.post("/")
def handle_message(payload: OperatorRequest) -> OperatorResponse:
    now = datetime.now(timezone.utc).isoformat()

    with _sessions_lock:
        history = _sessions.setdefault(payload.sessionID, [])
        history.append({"role": "operator", "msg": payload.msg, "ts": now})

        reply = (
            f"OK. Sesja '{payload.sessionID}': zapisano wiadomość #{len(history)}. "
            f"Treść: {payload.msg}"
        )
        history.append({"role": "server", "msg": reply, "ts": now})

    return OperatorResponse(msg=reply)


if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=3000, reload=False)
