from __future__ import annotations

import json
import logging
import os
import pathlib
import sys
from datetime import datetime, timezone
from threading import RLock
from typing import Any, Dict, List, Iterable

from agno.agent import Agent
from agno.db.sqlite import SqliteDb
from agno.models.message import Message
from agno.models.openai import OpenAIResponses
from agno.tools.mcp import MCPTools

import uvicorn
from fastapi import FastAPI, Request
from pydantic import BaseModel, Field
from starlette.responses import Response

# --- logging to stdout ---
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s - %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger("app")

MCP_SERVER_URL = os.getenv("MCP_SERVER_URL")
print(f"{MCP_SERVER_URL=}")

centrala_mcp_server = MCPTools(
    url=MCP_SERVER_URL,
    transport="streamable-http"
)

agno_assist = Agent(
    name="Agno Assist",
    model=OpenAIResponses(
        id=os.getenv("OPENAI_MODEL"),
        service_tier="flex" if os.getenv("OPENAI_FLEX", "") == "true" else None,
    ),
    system_message=pathlib.Path("system_prompt.md").read_text("utf-8"),
    db=SqliteDb(db_file="agno.db"),                     # session storage
    tools=[centrala_mcp_server],  # Agno docs via MCP
    add_datetime_to_context=True,
    add_history_to_context=True,                         # include past runs
    num_history_runs=3,                                  # last 3 conversations
    markdown=True,
)
agno_assist.initialize_agent()

# In-memory session store: sessionID -> messages (conversation history)
# Each message is a dict for flexibility.
_sessions: Dict[str, List[Dict[str, Any]]] = {}
_sessions_lock = RLock()

# Disable autogenerated docs to keep the server effectively to a single endpoint.
app = FastAPI(docs_url=None, redoc_url=None, openapi_url=None)


def messages_to_dict(messages: Iterable[Message]) -> list[dict]:
    result: list[dict[str, str]] = []
    for message in messages:
        msg = {
            "role": message.role,
            "content": message.content,
            "tool_calls": message.tool_calls,
            "tool_args": message.tool_args,
            "tool_name": message.tool_name,
            "tool_call_error": message.tool_call_error
        }
        result.append({k:v for k,v in msg.items() if v})
    return result


@app.middleware("http")
async def log_request_response(request: Request, call_next):
    # request body
    req_body = await request.body()
    req_body_text = req_body.decode("utf-8", errors="replace")

    # call endpoint
    response = await call_next(request)

    # response body (consume iterator and rebuild response)
    resp_body = b""
    async for chunk in response.body_iterator:
        resp_body += chunk
    resp_body_text = resp_body.decode("utf-8", errors="replace")

    # logger.info(
    #     "REQ %s %s body=%s",
    #     request.method,
    #     str(request.url),
    #     req_body_text,
    # )
    # logger.info(
    #     "RESP %s %s status=%s body=%s",
    #     request.method,
    #     str(request.url),
    #     response.status_code,
    #     resp_body_text,
    # )

    return Response(
        content=resp_body,
        status_code=response.status_code,
        headers=dict(response.headers),
        media_type=response.media_type,
        background=response.background,
    )


class OperatorRequest(BaseModel):
    sessionID: str = Field(..., min_length=1)
    msg: str = Field(..., min_length=1)


class OperatorResponse(BaseModel):
    msg: str


@app.post("/")
async def handle_message(payload: OperatorRequest) -> OperatorResponse:

    # Sprawdź czy toolsy się zainicjalizowały
    await centrala_mcp_server.connect()
    await centrala_mcp_server.build_tools()

    # print(f"MCP Tools initialized: {centrala_mcp_server.initialized}")
    # print(f"Available tools: {list(centrala_mcp_server.functions.keys())}")

    now = datetime.now(timezone.utc).isoformat()

    with _sessions_lock:
        history = _sessions.setdefault(payload.sessionID, [])
        history.append({"role": "operator", "msg": payload.msg, "ts": now})
        response = await agno_assist.arun(
            input=Message(
                role="user",
                content=payload.msg
            ),
            session_id=payload.sessionID,
            # debug_mode=True
        )

        # response.t
        messages = messages_to_dict(response.messages)
        logger.info(f"\nSESJA: {payload.sessionID}\n{json.dumps(messages, indent=4, ensure_ascii=False)}")
        reply = (
            f"OK. Sesja '{payload.sessionID}': zapisano wiadomość #{len(history)}. "
            f"Treść: {payload.msg}"
        )
        history.append({"role": "server", "msg": response, "ts": now})

    return OperatorResponse(msg=response.messages[-1].content)


@app.get("/")
def handle_message2(payload) -> OperatorResponse:
    logger.info(f"WTF: {payload}")


if __name__ == "__main__":
    centrala_mcp_server.connect()
    centrala_mcp_server.build_tools()
    uvicorn.run("main:app", host="0.0.0.0", port=3000, reload=False)
